--USERS
INSERT INTO USER (USERNAME, PASSWORD, WAGE) VALUES('user', 'password', 1000);
INSERT INTO USER (USERNAME, PASSWORD, WAGE) VALUES('admin', 'password', 200);
INSERT INTO USER (USERNAME, PASSWORD, WAGE) VALUES('test@mail.com', '12345', 2430);
INSERT INTO USER (USERNAME, PASSWORD, WAGE) VALUES('new@mail.com', '12345', 4509);
INSERT INTO USER (USERNAME, PASSWORD) VALUES('user1', '145');
